### DISCUSSION TITLE
Creating a firewall rule with target “This Firewall” fails

### DISCUSSION THREAD

**Discussion by ZzenlD** [O-X-L/ansible-opnsense#131] [Q&A] [answered]
Hello,
I would like to allow DNS requests to the firewall for each subnet. In the Web UI, I can select “This Firewall” as the destination and everything works.

I have now created the following Ansible task for this
```yaml
- name: Allow DNS requests to the firewall
  ansibleguy.opnsense.rule:
    interface: LAN
    action: pass
    protocol: TCP
    destination_net: This Firewall
    destination_port: 53
    description: Allow DNS-Queries
    match_fields: ["description"]
    firewall: <host>
    api_key: <key>
    api_secret: <secret>
```

But now I get the error message `This Firewall is not a valid source IP address or alias.`.

Does anyone have a solution for this or what am I doing wrong?

**Comment by jiuka** [comment, marked as answer]
In the API this is refert to as  `(self)`. The following shoud work.

```
  - name: Allow DNS requests to the firewall
    ansibleguy.opnsense.rule:
      interface: LAN
      action: pass
      protocol: TCP
      destination_net: '(self)'
      destination_port: 53
      description: Allow DNS-Queries
      match_fields: ["description"]
      firewall: <host>
      api_key: <key>
      api_secret: <secret>
```
