### DISCUSSION TITLE
Match IP when using Unbound

### DISCUSSION THREAD

**Discussion by Bubbgump209** [O-X-L/ansible-opnsense#19] [Q&A] [answered]
For the life of me I can't get an IP to match when using the Unbound host-override.

```
- name: Remove DNS record from OPNsense1
        ansibleguy.opnsense.unbound_host:
          firewall: 'opnsense1'
          hostname: '{{ hostname[0] }}'
          domain: 'lan'
          value: '{{ HostIP_input }}'
          state: 'absent'
          match_fields: ['hostname', 'domain', 'value']
```

Here's some debug where the variable sure looks right to me:

```
TASK [Make FQDN into a fact] ***************************************************
ok: [localhost]

TASK [Lookup host] *************************************************************
ok: [localhost] => {
    "msg": "192.168.73.205"
}

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "HostIP_input": {
        "changed": false,
        "failed": false,
        "msg": "192.168.73.205"
    }
}

TASK [Calculate host name] *****************************************************
ok: [localhost]

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "hostname": [
        "deleteme4",
        "lan"
    ]
}

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "hostname[0]": "deleteme4"
}

TASK [Remove DNS record from OPNsense1] ****************************************
ok: [localhost]

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "wtf": {
        "changed": false,
        "diff": {},
        "failed": false
    }
}
```
Note the "Lookup host" step is querying Unbound to get the IP - so I know it is correct.
What do I have to do to get the IP to match 'value'?
