### DISCUSSION TITLE
Why a "reload" attribute?  And why is it's default true?

### DISCUSSION THREAD

**Discussion by ptoal** [O-X-L/ansible-opnsense#238] [Q&A] [answered]
I noticed that there are two ways to 'reload' (I suspect this is like hitting the "apply" button in the UI) the state of an opnsense module/service.  This seems to be an anti-pattern to me, from an Ansible perspective, so I'm curious why it's there?  Also, why is it defaulted to true?  It's more intuitive to me that it would default to 'false', and that the a playbook would use a handler to reload the service.  Just curious about the design, here?

**Comment by superstes** [comment]
Users had issues as they did not expect to call another module to manually `apply` the changes.
They might expect a `fire and forget` behavior from an API.

I personally only recommend enabling it for the 'mass-management' modules (https://github.com/O-X-L/ansible-opnsense/issues/185) as they will only call it once all changes are done.

You should be able to easily change the default for you environment like this:

```yaml
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: "{{ lookup('ansible.builtin.env', 'TEST_FIREWALL') }}"
      api_credential_file: "{{ lookup('ansible.builtin.env', 'TEST_API_KEY') }}"
      reload: false
```
