### DISCUSSION TITLE
Wireguard add/remove a single peer from server

### DISCUSSION THREAD

**Discussion by NurPech** [O-X-L/ansible-opnsense#75] [Q&A]
Hi,

I need to deploy multiple appliances which will be connected via wireguard to an opnsense. I need to create a peer and then add it to a specific server (instance). Currently I think that this is only possible when passing all peers to ansibleguy.opnsense.wireguard_server. But my staging playbook doesn't know which peers existing. As far as I know it is not possible to add or remove a peer from a server without the full peer-list. Am I missing something or does someone know a 'smart' way to archive this?

Regards
René

**Comment by ansibleguy** [comment]
Greetings.

You are right - when calling the `wireguard_server` module you have to pass all the peers you want to add to it.
You could open a feature-request for a `persist_peers` flag - if it would be a great enhancement for your edge-case. (or something like that)

As I see it - if your playbook does not known the 'whole truth', you might need to pull the existing peers beforehand and merge them with the one you want to add.

On first though I would think of two ways of doing this:

1. Using the `list` module:

  ```yaml
      - name: Listing
        ansibleguy.opnsense.list:
          target: 'wireguard_peer'
        register: existing_entries
  ```

2. Pre-running the same task in `check_mode` and using the `diff-before`

  ```yaml
      - name: Adding 3
        ansibleguy.opnsense.wireguard_server:
          ...
          peers: ['ANSIBLE_TEST_2_1']
        register: wg_srv
        check_mode: true

      - debug:
          var: wg_srv
  ```
  The output might look something like this:
  ````bash
    "wg_srv": {
        "changed": true,
        "diff": {
            "before": {
                ...
                "peers": [
                    "004bc7db-16ff-49b8-a566-3cf946f77482"
                ],
                ...
            },
            "after": {
                ...
            }
        },
        ...
    }
  ```
