### ISSUE TITLE
Problem: alias_purge not working with 'action: disable'

### ISSUE THREAD

**Issue by alexandredulche** [O-X-L/ansible-opnsense#111]
### Modules

alias_purge

### Version

```bash
ansibleguy.opnsense           1.2.11
```

### Ansible Version

```bash
ansible [core 2.15.4]
python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
jinja version = 3.1.2
libyaml = True
```

### OPNSense Version

```bash
24.7.7
```

### Issue

The purge_all module works as expected in "action: delete" mode. 
However it fails to disable aliases when using "action: disable".

It shows that the filter applies correctly, but in OpnSense WebUI, the alias is still enabled, 

`
TASK [Disable all non-configured aliases] ******************************************************************************************************************************************************
[WARNING]: Purging alias 'test4'!
changed: [localhost]
`

I also tested ansibleguy.opnsense.alias_multi with "enable: false" and it's working, aliases are created but disabled.

### Config Ansible

```yaml
tasks:

- name: 'Create aliases'
  ansibleguy.opnsense.alias_multi:
    fail_verification: true 
    fail_processing: true
    output_info: true
    reload: false
    enabled: true
    aliases:
      test1:
        content: '1.1.1.1'
      test2:
        content: ['1.1.1.1', '1.1.1.2']
        description: 'to be deleted'
      test3:
        type: 'network'
        content: '10.0.0.0/24'
        description: 'to be disabled'
      test4:
        type: 'network'
        content: 'test3'
  notify: Reload aliases


- name: Disable all non-configured aliases
  ansibleguy.opnsense.alias_purge:
    aliases: 
      test1:
      test2:
      test3:
    action: disable 
    fail_all: true
    output_info: true
    reload: false
  notify: Reload aliases

handlers:

  - name: 'Reload aliases'
    ansibleguy.opnsense.reload:
      target: alias
```
