### ISSUE TITLE
Problem: Unable to assign a Wireguard instance to peer

### ISSUE THREAD

**Issue by 3isenHeiM** [O-X-L/ansible-opnsense#150]
### Modules

`ansibleguy.opnsense.wireguard_peer`

### Version

```bash
ansibleguy.opnsense 1.2.12
```

### Ansible Version

```bash
ansible [core 2.14.18]
```

### OPNSense Version

```bash
OPNsense 24.7.12_2-amd64
```

### OPNSense-Plugin Version

```bash

```

### Issue

The module does not allow to assign the current peer to a Wireguard instance.

There should be an `instance` parameter of this module to allow to create a peer **and associate it to an instance.**

### Config Ansible

```yaml

```

### Config OPNSense

```bash

```

### Debug Output

```bash

```

### Profiling Output

```bash

```

**Comment by ansibleguy** [comment]
I was not able to reproduce the issue.
The tests seem to work as expected:
* https://github.com/ansibleguy/collection_opnsense/blob/latest/tests/wireguard_peer.yml
* https://github.com/ansibleguy/collection_opnsense/blob/latest/tests/wireguard_server.yml

Please review the examples and provide the Ansible-Tasks & -Config if the issue still is present.

**Comment by 3isenHeiM** [comment]
Currently, the process to create a Wireguard peer and server is done like this:
1. Create the peer
2. Create the server and assign the peer to it (using the `peers` field).

However I feel this is not the *optimal* way to do it...

IMHO, the wireguard sever and peer creation should be done this way:
1. Create the wireguard Server
2. Create a wireguard peer and assign it to a server

But currently, there isn't any field in `wireguard_peer` to associate a peer to an instance, at its creation.


My proposition would be to create a wireguard peer (after the wireguard server creation) with something like this:
```yaml
    - name: Adding peer
      ansibleguy.opnsense.wireguard_peer:
        name: 'test1'
        endpoint: 'wg.template.ansibleguy.net'
        allowed_ips: ['10.200.0.1/32']
        public_key: 'gTuhGXA28/qRSLPnH3szr2+A4l3C4tKlUsOORV63+SE='
        server: 'test1'
```

**Comment by ansibleguy** [comment]
You are right.
This should cover that functionality: [wireguard_peer tests - linking to servers/instances](https://github.com/ansibleguy/collection_opnsense/blob/latest/tests/wireguard_peer.yml#L213)

Feel free to test the new implementation on the latest version and report back if you find an issue with it: `ansible-galaxy collection install git+https://github.com/ansibleguy/collection_opnsense.git`

**Comment by ovv** [comment]
@ansibleguy While I understand this change it makes interacting with peers and servers kinda weird. If you want Idempotence you need to specify both the server peers and the peers servers.

```
- name: Configure server
  ansibleguy.opnsense.wireguard_server:
    name: "WG_SERVER_1"
    ...
   peers:
     - WG_PEER_1
     - WG_PEER_2

- name: Configure peer 1
  ansibleguy.opnsense.wireguard_peer:
    name: "WG_PEER_1"
    ...
    servers:
      - WG_SERVER_1

- name: Configure peer 2
  ansibleguy.opnsense.wireguard_peer:
    name: "WG_PEER_2"
    ...
    servers:
      - WG_SERVER_1
```

Maybe omitting the `peers` (in `wireguard_server`) or the `servers` (in `wireguard_peer`) shouldn't override the configuration or maybe deprecate/remove `wireguard_server.peers` ?
