### ISSUE TITLE
Problem: api_credential_file leaks api_key and api_secret

### ISSUE THREAD

**Issue by alteriks** [O-X-L/ansible-opnsense#187]
### Modules

ansibleguy.opnsense.all

### Version

```bash
all, 1.2.12
```

### Ansible Version

```bash
core 2.17.4
```

### OPNSense Version

```bash
25.1.1-amd64
```

### OPNSense-Plugin Version

```bash

```

### Issue

While using example from documentation 
```yaml
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: 'opnsense01.XXXX.XXXX'
      api_key: XXXX
      api_secret: XXXX
```
both values are masked, thanks to `no_log`
https://github.com/ansibleguy/collection_opnsense/blob/a534c2fe8ccb5df9d65393a6078594e5434c868e/plugins/module_utils/defaults/main.py#L13
https://github.com/ansibleguy/collection_opnsense/blob/a534c2fe8ccb5df9d65393a6078594e5434c868e/plugins/module_utils/defaults/main.py#L17
![Image](https://github.com/user-attachments/assets/a25b6eac-837d-41c9-b442-66685b60ff92)

Unfortunately using api_credential_file leaks api_key, api_secret in ansible logs
```yaml
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: 'opnsense01.XXXX.XXXX'
      api_credential_file: '/home/alteriks/git/acs/secrets/OPNsense01.XXXX.XXXX.key'

```
![Image](https://github.com/user-attachments/assets/88b76009-f3f8-4d01-bdb8-dd41d6bb7a62)

### Config Ansible

```yaml

```

### Config OPNSense

```bash

```

### Debug Output

```bash

```

### Profiling Output

```bash

```
