### ISSUE TITLE
Problem: wireguard not idempotent in 1.2.13

### ISSUE THREAD

**Issue by alteriks** [O-X-L/ansible-opnsense#192]
### Modules

wireguard

### Version

```bash
1.2.13
```

### Ansible Version

```bash
ansible [core 2.17.4]
  config file = /home/alteriks/git/acs/ansible.cfg
  configured module search path = ['/home/alteriks/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alteriks/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/alteriks/git/acs/galaxy
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### OPNSense Version

```bash
25.1
```

### OPNSense-Plugin Version

```bash

```

### Issue

After upgrading to version 1.2.13, which incorporates change from https://github.com/ansibleguy/collection_opnsense/commit/839d57d4e8f7b11a8fe00813e95840a23ec3e923
Wireguard module is not idempotent anymore.

Using following playbook:
```yaml
- hosts: localhost
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: "{{ opnsense_host }}"
      api_key: "{{ opnsense_api_key }}"
      api_secret: "{{ opnsense_api_secret }}"
  vars:
    ara_playbook_labels:
      - debug
      - opnsense
      - wireguard
    opnsense_host: "{{ opnsense01_host }}"
    opnsense_sops_path: "{{ opnsense01_sops_path }}"
  tasks:
    - name: Load encrypted credentials - opnsense
      community.sops.load_vars:
        file: "{{ opnsense_sops_path }}"
        expressions: ignore
      no_log: "{{ enable_no_log | default(true) }}"

    - ansibleguy.opnsense.wireguard_peer:
        name: 'peer1'
        endpoint: 'wg.template.ansibleguy.net'
        allowed_ips: ['10.200.0.1/32']
        public_key: 'gTuhGXA28/qRSLPnH3szr2+A4l3C4tKlUsOORV63+SE='

    - name: Adding server
      ansibleguy.opnsense.wireguard_server:
        name: 'test1'
        allowed_ips: ['10.200.0.1/32']
        peers: ['peer1']
        port: 51820
        public_key: 'gTuhGXA28/qRSLPnH3szr2+A4l3C4tKlUsOORV63+SE='
        private_key: 'gTuhGXA28/qRSLPnH3szr2+A4l3C4tKlUsOORV63+SE='
```

Version 1.2.12 is idempotent:

![Image](https://github.com/user-attachments/assets/a92b582b-bcbe-44af-8682-b23b2733c770)

Version 1.2.13 is NOT idempotent:

![Image](https://github.com/user-attachments/assets/2a15cc5b-4668-480c-9e2c-2a396e73c89f)

Details from 1.2.13

![Image](https://github.com/user-attachments/assets/c2d6ba24-31c7-40f4-b257-3f9799666938)

![Image](https://github.com/user-attachments/assets/8b4ccff4-3a9a-469e-acd8-1ba570c333ac)

### Config Ansible

```yaml

```

### Config OPNSense

```bash

```

### Debug Output

```bash

```

### Profiling Output

```bash

```
