### ISSUE TITLE
[unbound_host] Problems with matching

### ISSUE THREAD

**Issue by ansibleguy** [O-X-L/ansible-opnsense#20]
### Discussed in https://github.com/ansibleguy/collection_opnsense/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **Bubbgump209** June 29, 2023</sup>
For the life of me I can't get an IP to match when using the Unbound host-override.

```
- name: Remove DNS record from OPNsense1
        ansibleguy.opnsense.unbound_host:
          firewall: 'opnsense1'
          hostname: '{{ hostname[0] }}'
          domain: 'lan'
          value: '{{ HostIP_input }}'
          state: 'absent'
          match_fields: ['hostname', 'domain', 'value']
```

Here's some debug where the variable sure looks right to me:

```
TASK [Make FQDN into a fact] ***************************************************
ok: [localhost]

TASK [Lookup host] *************************************************************
ok: [localhost] => {
    "msg": "192.168.73.205"
}

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "HostIP_input": {
        "changed": false,
        "failed": false,
        "msg": "192.168.73.205"
    }
}

TASK [Calculate host name] *****************************************************
ok: [localhost]

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "hostname": [
        "deleteme4",
        "lan"
    ]
}

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "hostname[0]": "deleteme4"
}

TASK [Remove DNS record from OPNsense1] ****************************************
ok: [localhost]

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => {
    "wtf": {
        "changed": false,
        "diff": {},
        "failed": false
    }
}
```
Note the "Lookup host" step is querying Unbound to get the IP - so I know it is correct.
What do I have to do to get the IP to match 'value'?</div>

**Comment by ansibleguy** [comment]
Greetings @Bubbgump209

If you don't use round-robin DNS-records the matching via 'hostname' + 'domain' should be enough.
> Docs: Fields that are used to match configured host-overrides with the running config - if any of those fields are changed, the module will think it’s a new entry

Your debug information is missing some important details.
Please run the following tasks and provide their output:

```yaml
- name: Adding record
  ansibleguy.opnsense.unbound_host:
    firewall: 'opnsense1'
    hostname: 'test'
    domain: 'lan'
    value: '192.168.111.222'
    state: 'present'
    match_fields: ['hostname', 'domain']

- name: Deleting record
  ansibleguy.opnsense.unbound_host:
    firewall: 'opnsense1'
    hostname: 'test'
    domain: 'lan'
    state: 'absent'
    match_fields: ['hostname', 'domain']
    debug: true  # the module will output some internal information that can be useful to understand why it does what it does
```

\- AnsibleGuy

**Comment by Bubbgump209** [comment]
The debug:true was very helpful. The module is not parsing JSON on the way in apparently and takes the JSON from a fact or variable as a raw string - thus the issue.

```
TASK [Echo IP fact] *********************************************************************************************************************
ok: [localhost] => {
    "IPfact": {
        "changed": false,
        "failed": false,
        "msg": "192.168.1.124"
    }
}
...
[WARNING]: NOT MATCHING: '192.168.1.124' != '{'msg': '192.168.1.124', 'failed': False, 'changed': False}'
```
 However if I simply use a string hard coded in the module, it works as expected. This feels like a bug as facts and vars are pretty core to Ansible?

**Comment by NiceRath** [comment]
We are using it in dictionary-format without any issues.

```yaml
- name: "OPNSENSE | DNS | {{ domain }} | Add hosts override"
  ansibleguy.opnsense.unbound_host:
    domain: "{{ domain }}"
    hostname: "{{ item.key }}"
    value: "{{ item.value.ip | default(item.value) }}"
    record_type: "{% if 'type' in item.value %}\
    {{ item.value.type }}\
    {% elif item.value.ip | default(item.value) | ansible.utils.ipv4 %}\
    A\
    {% else %}\
    AAAA\
    {% endif %}"
    reload: false
  with_dict: {'test1': {'ip': '192.168.1.1'}, 'test2': {'ip': '192.168.2.2'}}
```

Anyways => the 'value' field should be set to an IP-address if 'type' != 'MX'

I'm not sure why this value in invalid format is not throwing a validation error:
```python3
# https://github.com/ansibleguy/collection_opnsense/blob/latest/plugins/module_utils/main/unbound_host.py
        if self.p['record_type'] == 'MX':
            if not valid_hostname(self.p['value']):
                self.m.fail_json(f"Value '{self.p['value']}' is not a valid hostname!")

        else:
            self.p['prio'] = None

            if self.p['state'] == 'present' and not is_ip(self.p['value']):
                self.m.fail_json(f"Value '{self.p['value']}' is not a valid IP-address!")
```

**Comment by ansibleguy** [comment]
Greetings.

@Bubbgump209 It looks to me that you are supplying the wrong data to the module.
I'm still missing the whole YAML tasks + config to say it for sure, but try using 'IPfact.msg' as 'value'. (instead of the whole dict)
```
    - name: Test
      ansibleguy.opnsense.unbound_host:
        hostname: 'host'
        domain: 'opnsense.test.ansibleguy.net'
        value: "{{ IPfact.msg }}"
```

@NiceRath I just checked the validation and it seems to throw an error if such wrong input-data is provided:
```bash
failed: [localhost] (item={...}, "msg": "Value '{'msg': '192.168.0.1', 'invalid': 'data'}' is not a valid IP-address!"}
```

\- AnsibleGuy
