### ISSUE TITLE
Problem: error when adding custom CA for acme client

### ISSUE THREAD

**Issue by GBBx** [O-X-L/ansible-opnsense#241]
### Modules

ansibleguy.opnsense.acme_account

### Version

```bash
1.2.14
```

### Ansible Version

```bash
ansible [core 2.18.6]
```

### OPNSense Version

```bash
25.1.8_1
```

### OPNSense-Plugin Version

```bash
4.9
```

### Issue

hi, I have a playbook that uses the acme_account module:

```
- name: "install acme client"
  hosts: "all"
  connection: local
  gather_facts: no
  module_defaults: {group/ansibleguy.opnsense.all: {api_credential_file: "{{ inventory_hostname }}.key", firewall: "{{ ansible_host }}", ssl_verify: false, api_port: 443}}
  tags: acme_client
  tasks:
    - name: "test"
      ansibleguy.opnsense.acme_account:
        name: "test"
        enabled: true
        email: "example@example.com"
        ca: "custom"
        custom_ca: ["https://example.com/acme/directory"]
```

If I execute it I get this message:
```
FAILED! => {"changed": false, "msg": "ca is custom but all of the following are missing: c, u, s, t, o, m, _, c, a"}```

### Config Ansible

```yaml

```

### Config OPNSense

```bash

```

### Debug Output

```bash
FAILED! => {"changed": false, "msg": "ca is custom but all of the following are missing: c, u, s, t, o, m, _, c, a"}
```

### Profiling Output

```bash

```

**Comment by superstes** [comment]
Thank you for reporting this issue 👍 

This should now work on latest:

```yaml
    - name: Adding 2
      ansibleguy.opnsense.acme_account:
        name: 'ANSIBLE_TEST_1_2'
        ca: custom
        email: example@example.com
        custom_ca: 'https://example.com/acme/directory'
```

Feel free to test it and report back if there are still any issue: `ansible-galaxy collection install git+https://github.com/O-X-L/ansible_opnsense.git`
