### ISSUE TITLE
Add unbound host override randomly missing hosts

### ISSUE THREAD

**Issue by Hr46ph** [O-X-L/ansible-opnsense#41]
### Modules

ansibleguy.opnsense.unbound_host
ansibleguy.opnsense.reload

### Version

```bash
ansibleguy.opnsense 1.2.7
```

### Ansible Version

```bash
ansible [core 2.16.1]
```

### OPNSense Version

```bash
23.7.10_1
```

### Issue

Adding 12 hosts to unbound host override for vm's that are deployed with fixed ip addresses.
Relevant piece of ansible code:
```
- name: Extract domain from FQDN
  set_fact:
    domain_name: "{{ inventory_hostname | regex_replace('^[^\\.]+\\.', '') }}"
  delegate_to: localhost

- name: Adding build hosts to opnSense Unbound host overrides
  ansibleguy.opnsense.unbound_host:
    hostname: "{{ inventory_hostname | split('.') | first }}"
    domain: "{{ domain_name }}"
    value: "{{ ks.ip_address }}"
  delegate_to: localhost
  delegate_facts: true

- name: Reloading Unbounda
  ansibleguy.opnsense.reload:
    target: 'unbound'
  delegate_to: localhost
  delegate_facts: true
  run_once: true
```
Task output:
```
TASK [configure_system : Adding build hosts to opnSense Unbound host overrides] ******************************
Saturday 23 December 2023  18:37:02 +0100 (0:00:00.070)       0:00:00.100 ***** 
changed: [rocky-client-test-03.lab.domain.net -> localhost]
changed: [rocky-client-test-02.lab.domain.net -> localhost]
changed: [rocky-client-test-01.lab.domain.net -> localhost]
changed: [rocky-client-test-04.lab.domain.net -> localhost]
changed: [rocky-client-test-05.lab.domain.net -> localhost]
changed: [rocky-client-test-09.lab.domain.net -> localhost]
changed: [rocky-client-test-10.lab.domain.net -> localhost]
changed: [rocky-client-test-08.lab.domain.net -> localhost]
changed: [rocky-client-test-07.lab.domain.net -> localhost]
changed: [rocky-client-test-06.lab.domain.net -> localhost]
changed: [rocky-client-test-11.lab.domain.net -> localhost]
changed: [rocky-client-test-12.lab.domain.net -> localhost]
```
The result in opnSense:
```
rocky-client-test-02 lab.domain.net A (IPv4 address) 10.0.0.22
rocky-client-test-03 lab.domain.net A (IPv4 address) 10.0.0.23
rocky-client-test-06 lab.domain.net A (IPv4 address) 10.0.0.26
rocky-client-test-07 lab.domain.net A (IPv4 address) 10.0.0.27
rocky-client-test-10 lab.domain.net A (IPv4 address) 10.0.0.30
rocky-client-test-11 lab.domain.net A (IPv4 address) 10.0.0.31
rocky-client-test-12 lab.domain.net A (IPv4 address) 10.0.0.32
```
Then I run it again and the output says:
```
TASK [configure_system : Adding build hosts to opnSense Unbound host overrides] ******************************
Saturday 23 December 2023  18:46:54 +0100 (0:00:00.066)       0:00:00.096 ***** 
ok: [rocky-client-test-03.lab.domain.net -> localhost]
ok: [rocky-client-test-02.lab.domain.net -> localhost]
ok: [rocky-client-test-07.lab.domain.net -> localhost]
ok: [rocky-client-test-06.lab.domain.net -> localhost]
changed: [rocky-client-test-05.lab.domain.net -> localhost]
changed: [rocky-client-test-04.lab.domain.net -> localhost]
changed: [rocky-client-test-01.lab.domain.net -> localhost]
changed: [rocky-client-test-09.lab.domain.net -> localhost]
changed: [rocky-client-test-08.lab.domain.net -> localhost]
ok: [rocky-client-test-12.lab.domain.net -> localhost]
ok: [rocky-client-test-10.lab.domain.net -> localhost]
ok: [rocky-client-test-11.lab.domain.net -> localhost]
```
In opnsense it adds:
```
rocky-client-test-04 lab.domain.net	A (IPv4 address) 10.0.0.24
rocky-client-test-08 lab.domain.net	A (IPv4 address) 10.0.0.28
```
I run it again and the task throws an error:
```
TASK [configure_system : Adding build hosts to opnSense Unbound host overrides] ******************************
Saturday 23 December 2023  18:48:40 +0100 (0:00:00.062)       0:00:00.093 ***** 
ok: [rocky-client-test-04.lab.domain.net -> localhost]
ok: [rocky-client-test-03.lab.domain.net -> localhost]
ok: [rocky-client-test-02.lab.domain.net -> localhost]
ok: [rocky-client-test-06.lab.domain.net -> localhost]
ok: [rocky-client-test-07.lab.domain.net -> localhost]
ok: [rocky-client-test-08.lab.domain.net -> localhost]
ok: [rocky-client-test-10.lab.domain.net -> localhost]
ok: [rocky-client-test-11.lab.domain.net -> localhost]
fatal: [rocky-client-test-01.lab.domain.net -> localhost]: FAILED! => changed=false 
  msg: 'API call failed | Response: {''status_code'': 500, ''headers'': Headers({''content-type'': ''application/json;charset=utf-8'', ''strict-transport-security'': ''max-age=31536000'', ''content-length'': ''603'', ''date'': ''Sat, 23 Dec 2023 17:48:43 GMT'', ''server'': ''OPNsense''}), ''_request'': <Request(''POST'', ''https://singularity.internal.domain.net/api/unbound/service/reconfigure'')>, ''next_request'': None, ''extensions'': {''http_version'': b''HTTP/1.1'', ''reason_phrase'': b''Internal Server Error'', ''network_stream'': <httpcore._backends.sync.SyncStream object at 0x106549fd0>}, ''history'': [], ''is_closed'': True, ''is_stream_consumed'': True, ''default_encoding'': ''utf-8'', ''stream'': <httpx._client.BoundSyncStream object at 0x106588f10>, ''_num_bytes_downloaded'': 603, ''_decoder'': <httpx._decoders.IdentityDecoder object at 0x106588410>, ''_elapsed'': datetime.timedelta(microseconds=737992), ''_content'': b''{"errorMessage":"Template generation failed for internal
    service \\"unbound\\". See backend log for details.","errorTrace":"#0 [internal function]: OPNsense\\\\Base\\\\ApiMutableServiceControllerBase->reconfigureAction()\\n#1 [internal function]: Phalcon\\\\Dispatcher\\\\AbstractDispatcher->callActionMethod(Object(OPNsense\\\\Unbound\\\\Api\\\\ServiceController), \''reconfigureActi...\'', Array)\\n#2 [internal function]: Phalcon\\\\Dispatcher\\\\AbstractDispatcher->dispatch()\\n#3 /usr/local/opnsense/www/api.php(24): Phalcon\\\\Mvc\\\\Application->handle(\''/api/unbound/se...\'')\\n#4 {main}","errorTitle":"Configuration exception"}'', ''_encoding'': ''utf-8'', ''_text'': ''{"errorMessage":"Template generation failed for internal service \\"unbound\\". See backend log for details.","errorTrace":"#0 [internal function]: OPNsense\\\\Base\\\\ApiMutableServiceControllerBase->reconfigureAction()\\n#1 [internal function]: Phalcon\\\\Dispatcher\\\\AbstractDispatcher->callActionMethod(Object(OPNsense\\\\Unbound\\\\Api\\\\ServiceController), \''reconfigureActi...\'',
    Array)\\n#2 [internal function]: Phalcon\\\\Dispatcher\\\\AbstractDispatcher->dispatch()\\n#3 /usr/local/opnsense/www/api.php(24): Phalcon\\\\Mvc\\\\Application->handle(\''/api/unbound/se...\'')\\n#4 {main}","errorTitle":"Configuration exception"}''}'
ok: [rocky-client-test-12.lab.domain.net -> localhost]
^C [ERROR]: User interrupted execution
```
I run it again, final host is added (not posting task output its what you'd expect). In opnsense I got all 12 hosts now.

### Config Ansible

```yaml
[defaults]
interpreter_python = auto_silent
stdout_callback = yaml
inventory = ./inventory.ini
roles_path = ./roles
library = ./modules
collections_path = ./collections
vault_password_file = ../.packer_deploy_vaultpass
host_key_checking = false
remote_tmp = /tmp/$USER/ansible
callbacks_enabled = timer, profile_tasks
become_method = sudo
become_user = root
```
```


### Config OPNSense

```bash
Im not sure what to post? The entire opnsense xml would show way too much private info. Ask specifics and I can post those.
```

### Debug Output

```bash
The error appeared only once. Most of the runs, it adds one or more hosts without error.
```

**Comment by ansibleguy** [comment]
Greetings @Hr46ph !
Please try to add `reload: false` to the `unbound_host` task:

```yaml
- name: Adding build hosts to opnSense Unbound host overrides
  ansibleguy.opnsense.unbound_host:
    hostname: "{{ inventory_hostname | split('.') | first }}"
    domain: "{{ domain_name }}"
    value: "{{ ks.ip_address }}"
    reload: false
  vars:
    domain_name: "{{ inventory_hostname | regex_replace('^[^\\.]+\\.', '') }}"
  delegate_to: localhost
  delegate_facts: true
```

Else it will still perform a service-reload for each item/entry.
As unbound is known to be slow on reload it could explain the randomness of your problem.

Maybe you also should add `throttle: 1` to the task, so the API-calls are processed one after another.
If I remember correctly we already had an issue where the API did not handle simultaneous calls correctly.

```yaml
- name: Adding build hosts to opnSense Unbound host overrides
  ansibleguy.opnsense.unbound_host:
    hostname: "{{ inventory_hostname | split('.') | first }}"
    domain: "{{ domain_name }}"
    value: "{{ ks.ip_address }}"
    reload: false
  vars:
    domain_name: "{{ inventory_hostname | regex_replace('^[^\\.]+\\.', '') }}"
  throttle: 1
  delegate_to: localhost
  delegate_facts: true
```
