### ISSUE TITLE
[frr_bgp_prefix_list] - Unable create prefix list with more subnets

### ISSUE THREAD

**Issue by FilipK-CZ** [O-X-L/ansible-opnsense#6]
## Basic info

- [x] Affected Module: 
frr_bgp_prefix_list

### Versions
* Controller
  - [x] Collection version: 

       (```ansible-galaxy collection list | grep opnsense```)
ansibleguy.opnsense 1.0.15
  - [x] Ansible version:

    (```python3 -m pip list | grep ansible``` or ```apt policy ansible```)
ansible-compat     2.2.0
ansible-core       2.13.4
ansible-lint       6.6.0
ansible-pylibssh   0.0.0
  - [x] Python version:
Python 3.10.8

* OPNSense

  - [x] System version: 
OPNsense 22.7.9-amd64

  - [x] Plugin version:
os-frr (installed) | 1.31

### Describe the bug

If you use the prefix list module, you cannot (by Opnsense design) create a list with multiple prefixes directly, and you must create multiple inserts with the same name but different sequence numbers. 

### Expected behavior

Try to mach prefix list name with seq number to change right rule

### Screenshots

![image](https://user-images.githubusercontent.com/7279856/205629106-dab17fc9-e3b1-4cee-8c9f-74a0fb2515a8.png)

### Tasks
Task(s) that produce the error:

```yaml
---
- name: Creating prefix-list
  ansibleguy.opnsense.frr_bgp_prefix_list:
    name: "{{ prefix.name }}"
    network: "{{ item.network }}"
    seq: "{{ item.seq }}"
    action: "{{ item.action }}"
  loop: "{{ prefix.networks }}"
```
```yaml
    - name: Creating BGP prefix-list
      include_tasks: "tasks/opnsense-prefix_list-each.yaml"
      loop: "{{ opnsense_bgp_prefix_lists }}"
      loop_control:
        loop_var: prefix
        label: "{{ prefix.name }}"
```

### Config
Config used for the task(s):

```yaml
opnsense_bgp_prefix_lists:
  - name: "AdvertiseNewNetwork"
    networks:
      - network: "10.7.120.0/28"
        seq: 100
        action: 'permit'
      - network: "10.0.255.48/28"
        seq: 101
        action: 'permit'
```
