### ISSUE TITLE
Problem: Unbound DNS-over-TLS should not require a domain

### ISSUE THREAD

**Issue by calvinbui** [O-X-L/ansible-opnsense#63]
### Modules

ansibleguy.opnsense.unbound_dot

### Version

```bash
1.2.8
```

### Ansible Version

```bash
ansible [core 2.16.3]
python version = 3.10.12
```

### OPNSense Version

```bash
24.1.2_1
```

### Issue

It is valid to not have a domain to forward all queries.

![image](https://github.com/ansibleguy/collection_opnsense/assets/3604363/5effa7d5-9e5e-439b-bda1-53a448021182)

```
failed: [localhost] (item={'address': '9.9.9.9', 'hostname': 'dns.quad9.net'}) => {"ansible_loop_var": "item", "changed": false, "item": {"address": "9.9.9.9", "hostname": "dns.quad9.net"}, "msg": "Value '' is an invalid domain!"}
```

Even when I list `unbound_dot`, it is the case:

```
{"domain": "", "enabled": true, "port": 853, "target": "9.9.9.9", "uuid": "<redacted>", "verify": "dns.quad9.net"}
```

### Config Ansible

```yaml
- name: Unbound DNS-over-TLS
      ansibleguy.opnsense.unbound_dot:
        domain: "{{ item.domain | default('') }}"
        target: "{{ item.address }}"
        port: "853"
        verify: "{{ item.hostname }}"
      loop:
        -
          address: 9.9.9.9
          hostname: dns.quad9.net
```

### Debug Output

```bash
N/A
```
