### ISSUE TITLE
Problem: Unable to see Key file when using via docker

### ISSUE THREAD

**Issue by SvartrShell** [O-X-L/ansible-opnsense#66]
### Modules

NA

### Version

```bash
stable
```

### Ansible Version

```bash
stable
```

### OPNSense Version

```bash
latest
```

### OPNSense-Plugin Version

```bash
NA
```

### Issue

Been plugging away at this for days and am just hitting a wall. I have a docker semaphore install. The requirements and such are all working fine, it just cant see the api key file

For the purposes of testing this - the key file is in the same repo as the playbook

i have tried 
      api_credential_file: '{{ playbook_dir }}/testkey.key'
       api_credential_file: './testkey.key'

all i want to do is get it to restart unbound and a few other services but having a right nightmare
            
            

### Config Ansible

```yaml
- name: Restart Unbound on OpnSense Hosts
  hosts: "{{ hosts | default('all') }}"
  gather_facts: no
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: "{{ ansible_host }}"
      api_credential_file: '{{ playbook_dir }}/testkey.key'

  tasks:
    - name: Restarting Unbound DNS service
      ansibleguy.opnsense.service:
        name: 'unbound'
        action: 'restart'
```

### Config OPNSense

```bash
NA
```

### Debug Output

```bash
FAILED! => {"changed": false, "msg": "Provided 'api_credential_file' at path '/tmp/semaphore/repository_1_29/playbooks/testing/testkey.key' does not exist!"}
1:04:42 PM
```
