### ISSUE TITLE
Problem: unbound_host - duplicate entries

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/ansible-opnsense#70]
### Modules

unbound_host

### Version

```bash
1.2.8
```

### Ansible Version

```bash
ansible [core 2.16.4]
```

### OPNSense Version

```bash
OPNsense 24.1.2_1-amd64
```

### Issue

The module does not recognize when an override already exists. It re-creates them every time.
We have 100+ of them.

### Config Ansible

```yaml
- name: "OPNSENSE | DNS | {{ domain }} | Add hosts override"
  ansibleguy.opnsense.unbound_host:
    domain: "{{ domain }}"
    hostname: "{{ item.key }}"
    value: "{{ item.value.ip | default(item.value) }}"
    record_type: "{% if 'type' in item.value %}\
    {{ item.value.type }}\
    {% elif item.value.ip | default(item.value) | ansible.utils.ipv4 %}\
    A\
    {% else %}\
    AAAA\
    {% endif %}"
    reload: false
    debug: true
  with_dict: "{{ hosts }}"
```

### Debug Output

```bash
Contains too much information
```
