### ISSUE TITLE
Problem: update of the 'content' field for the alias doesn't work as expected

### ISSUE THREAD

**Issue by rhaido** [O-X-L/ansible-opnsense#71]
### Modules

alias

### Version

```bash
ansibleguy.opnsense 1.2.8
```

### Ansible Version

```bash
ansible [core 2.14.3]
```

### OPNSense Version

```bash
24.1.3_1
```

### Issue

Dear Ansible Guy,

It seems, that update of an alias is not really working correctly. I have the following situation:

```
vars/test.yml:
  - { name: "LIST", type: "urltable", content: ['https://ex.net/test'], ufq: 0.5 }
```
  
Playbook:

```
- hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/test.yml
  module_defaults:
    group/ansibleguy.opnsense.all:
      ...

  tasks:
    - name: Configure Firewall Aliases
      ansibleguy.opnsense.alias:
        name: "{{ item.name }}"
        type: "{{ item.type }}"
        content: "{{ item.content }}"
        updatefreq_days: "{{ item.ufq }}"
        state: "{{ item.state | default('present') }}"
        reload: true
      with_items: "{{ aliases }}"
```
If I run the playbook with ```ansible-playbook -D opnsense.yml``` it gives me OK, but doesn't change the value of LIST alias. Is it the expected behaviour? Creation works as expected though.

Thanks!
M.

### Config Ansible

```yaml
no special configuration used
```

### Debug Output

```bash
PLAY [localhost] ***********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [localhost]

TASK [Configure Firewall Aliases] ******************************************************************************************************
ok: [localhost] => (item={'name': 'LIST', 'type': 'urltable', 'content': ['https://ex.net/test'], 'ufq': 0.5})

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
