### ISSUE TITLE
Problem: package module tests fail

### ISSUE THREAD

**Issue by ansibleguy** [O-X-L/ansible-opnsense#72]
### Modules

package

### Version

```bash
latest
```

### Ansible Version

```bash
-
```

### OPNSense Version

```bash
latest
```

### OPNSense-Plugin Version

```bash
-
```

### Issue

The task always fails. If I run it manually on the same box - it works. Disabled it for now so the other tests can run

### Config Ansible

```yaml
- name: Checking if installed
   ansibleguy.opnsense.list:
   register: opn12
   failed_when: >
     opn12.failed or
     test_app1 not in opn12 | json_query('data[*].name') or
     test_app2 not in opn12 | json_query('data[*].name')
   when: not ansible_check_mode
```

### Debug Output

```bash
-
```
