### ISSUE TITLE
Problem: route - not idempotent

### ISSUE THREAD

**Issue by mbx64** [O-X-L/ansible-opnsense#99]
### Modules

route

### Version

```bash
ansibleguy.opnsense           1.2.10
```

### Ansible Version

```bash
ansible [core 2.15.12]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.9.19 (main, Aug 23 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### OPNSense Version

```bash
24.1
```

### Issue

When I use the following task to deploy a route:

```yaml
- name: Configure route
  ansibleguy.opnsense.route:
    network: 172.16.0.0/24
    gateway: LAN_GW
```

The route will be added again with each execution. So it does not seem to be idempotent with the default `match_fields` (`network` and `gateway`). When I view the created routes in the web GUI, I see that their gateways are not called just `LAN_GW`, but `LAN_GW - <GW_IP_ADDRESS>`. Maybe the idempotency problem is related to this fact.

**Comment by ansibleguy** [comment]
Greetings!

Thank you for reporting.

I was not yet able to reproduce the issue - see the test: https://github.com/ansibleguy/collection_opnsense/blob/latest/tests/route.yml#L50

Please add the `debug: true` argument to your execution and share the output.

**Comment by mbx64** [comment]
Sorry, my MRE was wrong. The idempotency issue arrises, when the name of the gateway contains a hyphen (`-`):

```yaml
- name: Configure route
  ansibleguy.opnsense.route:
    network: 172.16.0.0/24
    gateway: LAN-GW
```
